---
title: "About"
metaAlignment: left
coverMeta: out
date: "`r Sys.Date()`"
staticPage: True
---

Hardcore scientist with excellent communication skills, fast learner and critical thinker, dedicated, detail-oriented, analytical, and organized. My passion is to use my expertise in statistical learning and programming to deliver game-changing knowledge from data. 

I received B.S. in Applied Math from Peking University, after which I started graduate training at Boston University, working in [Computational Biomedicine (CBM)](http://www.bumc.bu.edu/compbiomed/), while jointly advised by [Evan](https://www.linkedin.com/in/w-evan-johnson-a234837a/) and [Giovanni](https://www.hsph.harvard.edu/giovanni-parmigiani/). Now I am about to enter (hopefully) the final year of my PhD. I worked with Baidu Search Engine Marketing Group as a data analyst intern during college, and later in 2017, with [Gene](https://www.linkedin.com/in/hyunjin-gene-shin-6456253/) at Takeda Pharmaceuticals as a summer data scientist. <!-- My work mainly involves 1) evaluating statistical learning models in genomic studies, especially in the presence of batch or study effects, and 2) developing mathematical models to address unwanted variation in integrating genomic data. -->


### Expertise & Interests

* Development and validation of predictive models 
* Linear modeling and feature selection with high-dimensional data
* Machine learning and deep learning, with applications in genomics, biomedical and/or healthcare data 
* Heterogeneity in genomic data, data integration, batch effect adjustment


### Education

* **Boston University** (Boston, MA; 2015/09 -- present)   
Ph.D. Candidate in Bioinformatics 
* **Boston University** (Boston, MA; 2015/09 -- 2017/09)    
M.S. in Bioinformatics
* **Peking University** (Beijing, China; 2011/09 -- 2015/07)    
B.S. in Applied Mathematics      
Minor in Psychology


### Experience

* **Computational Biomedicine, Boston University** (Boston, MA; 2016/05 -- present)  
Research Assistant
* **Takeda Data Science Institute, Takeda Pharmaceuticals** (Cambridge, MA; 2017/06 -- 2017/08)      
Bioinformatics Scientist Intern
* **Search Engine Marketing, Baidu Inc.** (Beijing, China; 2014/06 -- 2014/09)    
Data Analyst Intern 
* **Biostatistics & Computational Biology, Dana-Farber Cancer Institute** (Boston, MA; 2016/05 -- 2018/05)  
Graduate Research Student
* **Boston University** (Boston, MA; 2017/09 -- 2017/12)  
Teaching Assistant, BF527 Application in Bioinformatics (machine learning lecturer)


### Skills

* **Data Science**:  
Machine Learning, Deep Learning, Data Mining, Multivariate Statistical Analysis, High
Dimensional Data Analysis, Hypothesis Testing, (Generalized) Linear Models, Bayesian Methods, Survival
Analysis, Time Series Analysis 
* **Programming**:  
R, Python, C, SQL, TensorFlow, MATLAB, Linux Shell Scripts, High-performance
Computing (with Hadoop MapReduce), Data Structures and Algorithms, Git Version Control


###  Contact
zhangyuqing DOT pkusms AT gmail DOT com  
Or message me on LinkedIn.
